steps:
  - id: "build-docker-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_VERSION}"
      - "-f"
      - "Dockerfile"
      - "."
    dir: "."

  - id: "push-docker-image-to-gcr"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_IMAGE_VERSION}"
    dir: "."

tags: ["$_PROJECT_ID", "$_IMAGE_NAME", "$_IMAGE_VERSION"]

options:
    dynamic_substitutions: true  

substitutions:
  _PROJECT_ID: "ingka-dpfwcbt-deploy-dev"
  _IMAGE_NAME: "resub-publish"
  _IMAGE_VERSION: "1.0.5"